# -*- coding: utf-8 -*-
"""HeightWeightAge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZotKHk2CQpHbj9s766dOuPHj6K82Ch1
"""

# !pip install matplotlib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/weight-height - weight-height.csv')
df

df=df.drop(['Gender'],axis=1)
df.head()

plt.scatter(df['Height'],df['Weight'])

plt.scatter(df['Age'],df['Weight'])

a=df['Height']
b=df['Age']
c=df['Weight']

x=[a,b]
y=c

x

y

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

x_train

x_test

len(x_train)

len(x_test)

from sklearn.linear_model import LinearRegression
clf=LinearRegression()

clf.fit(df[['Height','Age']],df.Weight)

clf.predict(x_test)

y_test

clf.score(x_test,y_test)

clf.predict([[69,60]])

import pickle

with open("model_pickle2","wb") as f:
  pickle.dump(clf,f)

with open("model_pickle2","rb") as f:
  mp=pickle.load(f)

mp.predict([[69,60]])

