# Generated by Django 4.1.5 on 2023-01-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(max_length=100),
        ),
    ]
