# Generated by Django 4.1.5 on 2023-01-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_forgot_password_token_profile_forget_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
            ],
        ),
    ]
