# Generated by Django 4.1.5 on 2023-01-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_table',
        ),
    ]
